
# 触发条件：在推送到 main 分支或提交 PR 时运行
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      # 第 1 步：下载你的代码到服务器
      - name: Checkout code
        uses: actions/checkout@v4

      # 第 2 步：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 第 3 步：安装所有依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 # 安装代码检查工具

      # 第 4 步：用 flake8 检查代码风格
      # 它会检查 src/ 目录下的所有 Python 文件
      - name: Lint with flake8
        run: flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics

      # 第 5 步：运行训练烟雾测试 (核心检查！)
      # 这一步确保你的 train.py 脚本对于 v0.1 和 v0.2 都能成功运行，
      # 证明你的核心逻辑没有被破坏。
      - name: Run Training Smoke Test
        run: |
          echo "--- Testing v0.1 training script ---"
          python src/train.py --version 0.1
          python src/train.py --version 0.2

