name: CI - Virtual Diabetes Clinic

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  MODEL_PATH: models/model_v0_2.joblib  # 替换成你实际的模型路径
  DOCKER_IMAGE: diabetes-api
  VERSION_TAG: v0.2  # 会用于命名镜像，自动与 Docker build 保持一致

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint code
        run: |
          flake8 app_v0_2.py tests

      - name: Run unit tests
        run: |
          pip install pytest
          pytest --junitxml=pytest-report.xml

      - name: Smoke test - load model
        run: |
          python -c "import joblib; m=joblib.load('${{ env.MODEL_PATH }}'); print('✅ Model loaded OK')"

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.VERSION_TAG }} .

      - name: Smoke test - run container
        run: |
          docker run -d -p 8000:8000 --name test_api ${{ env.DOCKER_IMAGE }}:${{ env.VERSION_TAG }}
          sleep 5
          curl -f http://127.0.0.1:8000/health || exit 1
          docker stop test_api

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: ${{ env.MODEL_PATH }}
