# .github/workflows/ci.yml

name: CI (Lint, Unit Test & Smoke Test)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 src tests --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Prepare for Unit Tests by running training
        run: |
          python src/train.py --version 0.1

      - name: Run Unit Tests with pytest
        run: pytest

      - name: Run Training Smoke Test
        run: |
          {
            echo "--- Testing v0.1 training script ---"
            python src/train.py --version 0.1
            echo ""
            echo "--- Testing v0.2 training script ---"
            python src/train.py --version 0.2 # <--- 这里已经被修正了！
          } > training_smoke_test_report.txt

      - name: Upload Smoke Test Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-report
          path: training_smoke_test_report.txt