name: CI (Lint, Test, Train Smoke)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest 

      - name: Lint with flake8
        run: flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Training Smoke Test
        run: |
          python src/train.py --version 0.1
          python src/train.py --version 0.2
