# .github/workflows/ci.yml
name: CI - Virtual Diabetes Clinic v0.1

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test - import model
        run: |
          python -c "import joblib; m=joblib.load('models/model_v0_1.joblib'); print('✅ Model loaded OK')"

      - name: Build Docker image
        run: docker build -t diabetes-api:v0.1 .

      - name: Run container smoke test
        run: |
          docker run -d -p 8000:8000 --name test_api diabetes-api:v0.1
          sleep 5
          curl -f http://127.0.0.1:8000/docs || exit 1
          docker stop test_api

